config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :bikes, only: [:index, :show, :new, :create] do
    resources :rentals, only: [:index, :create, :update, :show] do
      resources :payments, only: [:new, :create]
    end
    resources :profiles, only: [:show] do
    end
  end

  mount Attachinary::Engine => "/attachinary"

  get '/components', to: 'pages#components'
  get '/credits', to: 'pages#credits'

  root to: 'pages#home'

end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :rentals
  has_attachments :photo
  validates :children_seating_capacity, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  monetize :price_Øres
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show]

  def index
    @bikes = Bike.where.not(latitude: nil, longitude: nil)
    @bikes.each do |bike|
    (@markers ||= []).push [
                            bike.id,
                            bike.latitude,
                            bike.longitude,
                            bike.photo.first.public_id,
                            bike.price.fractional/100,
                            bike.price.currency.iso_code,
                            bike.brand_model.length > 21 ? bike.brand_model[0..21] + '…': bike.brand_model,
                            bike.caption.length > 25 ? bike.caption[0..25] + "…" : bike.caption
                            ]
    end
  end

  def show
    @rental = Rental.new
    @bike_coordinates = { lat: @bike.latitude, lng: @bike.longitude } # used for a JS test can be deleted.
    @hash = Gmaps4rails.build_markers(@bike) do |bike, marker|
      marker.lat bike.latitude
      marker.lng bike.longitude
    end
  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    if @bike.save
      redirect_to @bike
    else
      render :new
    end
  end

  private
  def set_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:color, :description_title, :description, :caption, :address, :zip_code, :city, :country, :brand_model, :brand, :brand_sku, :renter_must_have_experience_driving_cargo_bikes, :renter_must_have_experience_cycling_in_the_city, :renter_can_be_a_company, :has_seatbelt, :has_rain_cover, :box_has_bench, :is_electric, :children_seating_capacity, :gears_set, :light_set, :lock_set, :box_dimensions, :state, photo: [])
  end
end

app/views/bikes/_index_list.html.erb
<% @bikes.each do |bike|  %>

  <%= link_to bike_path(bike) do %>
    <div class="bike_index-card">
      <div class="bike_index-wrapper">
        <div class="bike_index-wrapper-picture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bike.photo.first.path, width: 287, height: 190,  crop: :fill; %>');">
          <div class="bike_index-picture">
            <%# cl_image_tag bike.photo.first.path, crop: :fit %>
            <%# cl_image_path bike.photo.first.path, crop: :fit %>
          </div>
          <div class="bike_index-caption">
            <%= bike.caption + "   " %>
          </div>
        </div>
        <div class="bike_index-wrapper-info">
          <div class="bike_index-wrapper-info-bike-wrapper">
            <div class="bike_index-heading">
              <!-- TODO make conditional for … -->
              <h3> <%= "#{bike.brand} #{bike.brand_model} #{bike.brand_sku}"[0..31] %> </h3>
            </div>
            <div class="bike_index-descr">
              <%= bike.description_title %>
            </div>
            <div class="bike_index-tags">
              <span>TagEx1</span> <span>TageE2</span>
            </div>
          </div>
          <div class="bike_index-wrapper-info-owner-wrapper">
            <div class="bike_index-wrapper-info-owner-content">
              <div class="bike_index-avatar">
                  <%= image_tag "hadrien", class: "avatar-large", alt: "hadrien" %>
              </div>
              <div class="bike_index-cartouche-wrapper">
                <div class="bike_index-cartouche-content">
                  <div class="bike_index-name">
                    <%= bike.user.anonymous %>
                    <% 5.times do %> <!-- TODO replace 5 by ratings # -->
                       <i class="bike_index-ratings fa fa-star" aria-hidden="true"></i>
                    <% end %>
                  </div>
                  <!-- <div class="bike_index-ratings">
                  </div> -->
                  <div class="bike_index-stats">
                    <div class="bike_index-stat">
                      <%= "92% accepted • 23 min response"[0..40]%>
                      <%# "92% accepted 23 min response"[0..40] + "…" %> <!-- TODO make conditional for … -->
                    </div>
                  </div>
                </div>
              </div>
              <div class="bike_index-price-wrapper">
                <div class="bike_index-price">
                  <%= humanized_money bike.price %>
                </div>
                <div class="bike_index-currency">
                  <%= bike.price.currency.iso_code + "/day" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <br>
<% end %>

app/views/bikes/_infowind.html.erb
<span>test</span>

app/views/bikes/_map.html.erb
<!-- <div id="map" style="width: 100%; height: calc(100vh - 70px);"></div> -->
<div id="map"></div>

<%= content_for(:after_js) do %>
  <script>
      $(document).ready(function() {
      function initMap() {
        // Display a map on the #map
        var map = new google.maps.Map(document.getElementById('map'), {});
        // Define bounds
        var bounds = new google.maps.LatLngBounds();
        // Define infoWindow
        var infoWindow = new google.maps.InfoWindow(); /* SINGLE */
        // Multiple markers
        var markers = <%= raw @markers.to_json %>
        for( i = 0; i < markers.length; i++) {
              var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
              bounds.extend(position);
              var marker = new google.maps.Marker({
                position: {lat: markers[i][1], lng: markers[i][2]},
                map: map,
                title: "marker id:" + markers[i][0]
              });
        // Set an infoWindow to each marker
         google.maps.event.addListener(marker, 'click', (function(marker, i) {
             return function() {
                 infoWindow.setContent(<%= render 'partial_maps' %>);
                 infoWindow.open(map, marker);
                  // Inject css to the infowindow
                  $('.bike_index_iw-wrapper').closest('.gm-style-iw').parent().addClass('custom-iw');
             }
         })(marker, i));
        // Center the map fitting all displayed markers
        map.fitBounds(bounds);
        }
        // Close any opened infoWindow by clicking anywhere (else) on the map
        google.maps.event.addListener( map, 'click', function() {
            infoWindow.open( null, null );
        } );
      }
      initMap();
      });
    </script>
<% end %>

app/views/bikes/_partial_maps.html.erb
'<div class="bike_index_iw-wrapper">' +
  '<div class="bike_index_iw-content">' +
    '<div class="bike_index_iw-picture-wrapper">' +
      '<img src="http://res.cloudinary.com/dchxwllhb/image/upload/c_fill,h_153,w_229/' + markers[i][3] + '" alt="" height="153" width="229">' +
    '</div>' +
    '<div class="bike_index_iw-price-wrapper">' +
      '<span class="bike_index_iw-price-wrapper-price">' +
        markers[i][4] +
      '</span>' +
      '<span class="bike_index_iw-price-wrapper-currency">' +
         markers[i][5] +
      '</span>' +
    '</div>' +
    '<div class="bike_index_iw-body-wrapper">' +
      '<div class="bike_index_iw-body-content">' +
        '<span class="bike_index_iw-body-content-avatar-wrapper">' +
            '<img class="avatar bike_index_iw-body-content-avatar" alt="" src="/assets/hadrien.jpg">' +
        '</span>' +
        '<div class="bike_index_iw-body-content-text-wrapper">' +
          '<div class="bike_index_iw-body-content-text-content">' +
            '<span class="bike_index_iw-body-content-text-content-title">' +
              markers[i][6] +
            '</span>' +
            '<span class="bike_index_iw-body-content-text-content-descr">' +
              markers[i][7]+
            '</span>' +
          '</div>' +
        '</div>' +
      '</div>' +
    '</div>' +
  '</div>' +
'</div>'

app/views/bikes/_show_booleans.html.erb
<i class="fa <%= @bike.renter_must_have_experience_driving_cargo_bikes ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
renter must have experience with cargo bikes
<br>
<i class="fa <%= @bike.renter_must_have_experience_cycling_in_the_city ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
renter must have experience cycling in a city
<br>
<i class="fa <%= @bike.renter_can_be_a_company ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
renter can be a company

app/views/bikes/_show_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <% @bike.photo.each_with_index do |photo, index| %>
            <% if index == 0 %>
              <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="active"></li>
            <% else %>
              <li data-target="#carousel-example-generic" data-slide-to="<%= index %>"</li>
            <% end %>
          <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <% @bike.photo.each_with_index do |photo, index| %>
            <% if index == 0 %>
              <div class="item active">
            <% else %>
              <div class="item">
            <% end %>
              <img src="<%= cl_image_path photo.path, width: 750, height: 500, crop: :fill %>" alt=""><!-- TODO build form for photo alt  -->
              <div class="carousel-caption">
                <!-- TODO build form for photo caption  -->
              </div>
            </div>
            <!-- <div class="item">
              <img src="..." alt="...">
              <div class="carousel-caption">
                ...
              </div>
            </div> -->
          <% end %>
        </div>

        <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <% unless @bike.photo.count < 2 %>
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        <% end %>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <% unless @bike.photo.count < 2 %>
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          <% end %>
          </a>
      </div>

app/views/bikes/_show_description.html.erb
<%= @bike.description %>

app/views/bikes/_show_map.html.erb
<!-- <div id="map" style="width: 100%; height: calc(100vh - 70px);"></div> -->
<div id="map"></div>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/bikes/_show_ratings.html.erb
"_show_ratings.html.erb"

app/views/bikes/_show_specs.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <table class="table table-condensed table-striped">
    <tbody class="small">
      <tr>
        <td class="col-xs-2">
          Has a seatbelt?
        </td>
        <td class="col-xs-2">
          <i class="fa <%= @bike.has_seatbelt ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Has a rain cover?
        </td>
        <td class="col-xs-2">
          <i class="fa <%= @bike.has_rain_cover ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Has a bench?
        </td>
        <td class="col-xs-2">
          <i class="fa <%= @bike.box_has_bench ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Is electric?
        </td>
        <td class="col-xs-2">
          <i class="fa <%= @bike.is_electric ? "fa-check-circle" : "fa-times-circle-o" %>" aria-hidden="true"></i>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Children seating capacity
        </td>
        <td class="col-xs-2">
          <%= @bike.children_seating_capacity.nil? ? "na" : @bike.children_seating_capacity %>
        </td>
      </tr>
    </tbody>
    </table>
  </div>
  <div class="col-xs-12 col-sm-6">
    <table class="table table-condensed table-striped">
    <tbody class="small">
      <tr>
        <td class="col-xs-2">
          Gears set
        </td>
        <td class="col-xs-2">
          <%= @bike.gears_set.empty? ? "na" : @bike.gears_set %>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Light set
        </td>
        <td class="col-xs-2">
          <%= @bike.light_set.empty? ? "na" : @bike.light_set %>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Lock set
        </td>
        <td class="col-xs-2">
          <%= @bike.lock_set.empty? ? "na" : @bike.lock_set %>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          Box dimensions
        </td>
        <td class="col-xs-2">
          <%= @bike.box_dimensions.empty? ? "na" : @bike.box_dimensions %>
        </td>
      </tr>
      <tr>
        <td class="col-xs-2">
          State
        </td>
        <td class="col-xs-2">
          <%= @bike.state.empty? ? "na" : @bike.state %>
        </td>
      </tr>
    </tbody>
    </table>
  </div>
</div>

app/views/bikes/index.html.erb
<div class="bike_index-container">

  <div class="bike_index-left-half">
    <%= render "index_list" %>
  </div>

  <div class="bike_index-right-half hidden-xs">
    <%= render "map" %>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    $(document.body).addClass('bike_index-body-noscroll');
  </script>
<% end %>

app/views/bikes/new.html.erb
<h1>Bikes#new</h1>
<%= simple_form_for @bike do |bike| %>
<%= bike.input :color %>
<%= bike.input :description_title %>
<%= bike.input :description %>
<%= bike.input :caption %>
<%= bike.input :address %>
<%= bike.input :zip_code %>
<%= bike.input :city %>
<%= bike.input :country %>
<%= bike.input :brand_model %>
<%= bike.input :brand_sku %>
<%= bike.input :brand %>
<%= bike.input :renter_must_have_experience_driving_cargo_bikes %>
<%= bike.input :renter_must_have_experience_cycling_in_the_city %>
<%= bike.input :renter_can_be_a_company %>
<%= bike.input :has_seatbelt %>
<%= bike.input :has_rain_cover %>
<%= bike.input :box_has_bench %>
<%= bike.input :is_electric %>
<%= bike.input :children_seating_capacity, input_html: { min: "0", max: "10" }%>
<%= bike.input :gears_set %>
<%= bike.input :light_set %>
<%= bike.input :lock_set %>
<%= bike.input :box_dimensions %>
<%= bike.input :state %>
<%= bike.input :photo, as: :attachinary %>
<%= bike.button :submit %>
<% end %>
<br>
<h1>TODO fix flow</h1>
<br>
<%= link_to image_tag('blue-on-light.png'), user_stripe_connect_omniauth_authorize_path %>

<%# content_for(:after_js) do %>
  <!-- <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key==#{ENV['GOOGLE_API_BROWSER_KEY']}"></script> -->
<%# end %>

app/views/bikes/show.html.erb
<div class="container bike_show">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <div class="bike_show-title-wrapper">
        <span class="bike_show-title">
          <%= @bike.brand %>
        </span>
        <span class="bike_show-subtitle">
          <%= @bike.brand_model %>
        <%= "#{@bike.brand_sku}"[0..31] %>
        <% 5.times do %> <!-- TODO replace 5 by ratings # -->
           <i class="bike_index-ratings fa fa-star" aria-hidden="true"></i>
        <% end %>
        </span>
      <br>
      <span class="bike_show-ownedby">
        Owned by <%= link_to "#{@bike.user.anonymous}", bike_profile_path(@bike, @bike.user) %>
      </span>
      </div>
      <%= render 'show_carousel' %>
       <div class="bike_show-description-wrapper">
       <p>Owner's description:</p>
       <h3><%= @bike.description_title %></h3>
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <%= render 'show_description' %>
          </div>
          <div class="col-xs-12 col-sm-6">
            <%= render 'show_booleans' %>
          </div>
        </div>
      </div>
      <hr>
      <p>Bike information:</p>
      <%= render 'show_specs' %>
      <hr>
      <%= render 'map' %>
      <hr>
      <%= render 'show_ratings' %>
      color: <%= @bike.color %> <br>
      <!-- description_title: <%= @bike.description_title %> <br>
      description: <%= @bike.description %> <br> -->
      caption: <%= @bike.caption %> <br>
      address: <%= @bike.address %> <br>
      zip code: <%= @bike.zip_code %> <br>
      city: <%= @bike.city %> <br>
      country: <%= @bike.country %> <br>
      price: <%= humanized_money_with_symbol(@bike.price) %> <br>

      <%= link_to "back to home", bikes_path %>
      <%# content_for(:after_js) do %>
        <!-- <script>
          $(document).ready(function() {
            var coord = <%= raw @bike_coordinates.to_json %>;
            alert('Bike coordinates are ' + coord.lat + ', ' + coord.lng);
          });
        </script> -->
      <%# end %>



    </div>
    <div class="col-xs-12 col-sm-4">
      <%= simple_form_for [@bike, @rental] do |f| %>
        <%= f.input :pick_up_date %>
        <%= f.input :return_date %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>