config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :bikes, only: [:index, :show, :new, :create] do
    resources :rentals, only: [:index, :create, :update, :show] do
      resources :payments, only: [:new, :create]
    end
    resources :profiles, only: [:show] do
    end
  end

  mount Attachinary::Engine => "/attachinary"

  get '/components', to: 'pages#components'
  get '/credits', to: 'pages#credits'

  root to: 'pages#home'

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_rental

  def new
  end

  def create
    customer = Stripe::Customer.create(
        source: params[:stripeToken],
        email:  params[:stripeEmail]
      )
    charge = Stripe::Charge.create(
        customer:     customer.id,
        amount:       @rental.amount_Øres,
        description:  "Payment for bike #{@rental.bike.brand_sku} for rental #{@rental.id} on carriage.dk",
        currency:     @rental.amount.currency
      )
    current_user.update(stripe_customer_id: customer.id)
    @rental.update(payment: charge.to_json, state: 'paid')
    # raise
    redirect_to bike_rental_path(@rental.bike, @rental)


    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_bike_rental_payment_path(@rental.bike, @rental)
  end

  private

  def set_rental
    @rental = Rental.where( state: 'pending').find(params[:rental_id])
  end
end

app/views/payments/create.html.erb
<h1>Payments#create</h1>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<h1>Payment for the rental of the bike <%= @rental.bike_sku %></h1>
<%= form_tag bike_rental_payments_path(@rental) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@rental.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= ENV['stripe_publishable_key'] %>"
    data-name="Renting a bike on carriage.dk"
    data-email="<%= current_user.email %>"
    data-description="Bike <%= @rental.bike_sku %>"
    data-amount="<%= @rental.amount_Øres %>"
    data-currency="<%= @rental.amount.currency %>"></script>
<% end %>